# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_show_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
